"""Pydantic models for red team agent outputs.

This module provides type-safe models for validating red team analysis outputs.
"""

from .enums import (
    AnalysisMode,
    Confidence,
    EvidenceType,
    FindingSeverity,
    Likelihood,
    MatchQuality,
    RiskCategoryName,
    Severity,
)
from .findings import (
    Evidence,
    Finding,
    GroundingNotes,
    Pattern,
    RiskCategory,
)
from .outputs import (
    # Attacker finding nested models
    AttackApplied,
    AttackerFinding,
    AttackerOutput,
    AttackResults,
    AttackSummary,
    # Context analysis models
    ClaimAnalysis,
    ContextAnalysisOutput,
    ContextAnalysisResults,
    DependencyChain,
    DependencyGraph,
    DetectedPattern,
    # Grounding nested models
    EvidenceReview,
    FindingEvidence,
    FindingImpact,
    FindingTarget,
    GroundingAssessment,
    GroundingIssue,
    GroundingOutput,
    GroundingResults,
    InferenceValidity,
    QuoteVerification,
    RiskSurface,
    SeverityCounts,
)
from .reports import (
    FindingsByLevel,
    Limitations,
    Methodology,
    Recommendations,
    RedTeamReport,
    RiskOverview,
)
from .strategy import (
    AttackerAssignment,
    AttackStrategyOutput,
    AttackStrategyResults,
    GroundingPlan,
    MetaAnalysisPlan,
    SelectedVector,
    StrategyTarget,
)

__all__ = [
    "AnalysisMode",
    "AttackApplied",
    "AttackResults",
    "AttackStrategyOutput",
    "AttackStrategyResults",
    "AttackSummary",
    "AttackerAssignment",
    "AttackerFinding",
    "AttackerOutput",
    "ClaimAnalysis",
    "Confidence",
    "ContextAnalysisOutput",
    "ContextAnalysisResults",
    "DependencyChain",
    "DependencyGraph",
    "DetectedPattern",
    "Evidence",
    "EvidenceReview",
    "EvidenceType",
    "Finding",
    "FindingEvidence",
    "FindingImpact",
    "FindingSeverity",
    "FindingTarget",
    "FindingsByLevel",
    "GroundingAssessment",
    "GroundingIssue",
    "GroundingNotes",
    "GroundingOutput",
    "GroundingPlan",
    "GroundingResults",
    "InferenceValidity",
    "Likelihood",
    "Limitations",
    "MatchQuality",
    "MetaAnalysisPlan",
    "Methodology",
    "Pattern",
    "QuoteVerification",
    "Recommendations",
    "RedTeamReport",
    "RiskCategory",
    "RiskCategoryName",
    "RiskOverview",
    "RiskSurface",
    "SelectedVector",
    "Severity",
    "SeverityCounts",
    "StrategyTarget",
]
